name: first_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/dé-1.png
    - assets/images/dé-2.png
    - assets/images/dé-3.png
    - assets/images/dé-4.png
    - assets/images/dé-5.png
    - assets/images/dé-6.png
  uses-material-design: true
